import type { Metadata } from "next";
import { buildPageMetadata } from "@/lib/seo";
import { getBreadcrumbSchema } from "@/lib/schema";
import { JsonLd } from "@/components/seo/JsonLd";
import { SiteShell } from "@/components/layout/SiteShell";
import { Breadcrumbs } from "@/components/shared/Breadcrumbs";
import { BRAND, SITE_URL } from "@/lib/constants";

export const metadata: Metadata = buildPageMetadata({
  title: "Privacy Policy | Junk Command",
  description:
    "Privacy policy for Junk Command junk removal — how we handle quote forms, photos, phone/SMS, and GoHighLevel CRM data for Port Huron customers.",
  path: "/privacy",
});

const UPDATED = "July 28, 2026";

export default function PrivacyPage() {
  const crumbs = [
    { name: "Home", href: "/" },
    { name: "Privacy Policy", href: "/privacy" },
  ];

  return (
    <SiteShell>
      <JsonLd data={getBreadcrumbSchema(crumbs)} />
      <section className="border-b border-[rgba(0,135,255,0.2)]">
        <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8">
          <Breadcrumbs items={crumbs} />
          <h1 className="mt-2 font-display text-4xl tracking-[0.06em] text-white sm:text-5xl">
            PRIVACY POLICY
          </h1>
          <p className="mt-4 text-sm text-muted">Last updated: {UPDATED}</p>
        </div>
      </section>

      <article className="mx-auto max-w-3xl space-y-10 px-4 py-12 text-muted sm:px-6 lg:px-8">
        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            WHO WE ARE
          </h2>
          <p>
            Junk Command (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;)
            provides junk removal and related services in Port Huron, St. Clair
            County, and surrounding Michigan communities. This Privacy Policy
            explains how we collect, use, and share information when you visit{" "}
            {SITE_URL}, request a quote, call or text us, or otherwise interact
            with our business.
          </p>
          <p>
            Contact:{" "}
            <a href={BRAND.emailHref} className="text-bright hover:text-white">
              {BRAND.email}
            </a>{" "}
            ·{" "}
            <a href={BRAND.phoneHref} className="text-bright hover:text-white">
              {BRAND.phone}
            </a>
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            INFORMATION WE COLLECT
          </h2>
          <p>We collect information you provide and information generated by your use of our site and communications channels:</p>
          <ul className="list-disc space-y-2 pl-5">
            <li>
              <span className="text-white">Contact details</span> — name, phone
              number, email address, service address, and city.
            </li>
            <li>
              <span className="text-white">Job details</span> — descriptions of
              junk to remove, preferred timing, access notes, and messages you
              send through forms, SMS, or email.
            </li>
            <li>
              <span className="text-white">Photos and media</span> — images or
              videos you upload or text us to help estimate volume and quote
              accurately. Do not upload images of unrelated third parties without
              permission or sensitive documents you do not intend to share.
            </li>
            <li>
              <span className="text-white">Technical data</span> — IP address,
              browser type, device information, referring pages, and general
              usage analytics cookies or similar technologies if enabled on our
              site.
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            HOW WE USE YOUR INFORMATION
          </h2>
          <ul className="list-disc space-y-2 pl-5">
            <li>Respond to quote requests and schedule junk removal jobs</li>
            <li>Estimate pricing from photos and job descriptions</li>
            <li>Communicate by phone, SMS, or email about your request</li>
            <li>Provide customer service and follow up after completed work</li>
            <li>Improve our website, routing, and service quality</li>
            <li>Comply with legal obligations and protect against fraud or abuse</li>
            <li>
              Send service-related messages; marketing texts only where permitted
              and with consent where required
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            CRM AND SERVICE PROVIDERS (INCLUDING GOHIGHLEVEL)
          </h2>
          <p>
            We use business tools to manage leads and customer communications,
            which may include GoHighLevel (GHL) or similar customer relationship
            management (CRM), form, and messaging platforms. Information you
            submit through quote forms, photo uploads, or conversations may be
            stored in those systems so our team can respond, schedule, and keep
            records of your job.
          </p>
          <p>
            Service providers process data on our behalf under contractual
            obligations to protect it and use it only for providing their
            services to us (hosting, CRM, SMS/email delivery, analytics, payment
            processing if applicable). We do not sell your personal information.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            PHONE, SMS, AND CALL RECORDING
          </h2>
          <p>
            When you call or text {BRAND.phone}, we use your number and message
            content to provide quotes and service. Message and data rates may
            apply. You can opt out of promotional SMS by following opt-out
            instructions in those messages (for example, replying STOP) where
            applicable. Operational messages about an active job may still be
            necessary to complete service you requested.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            COOKIES AND ANALYTICS
          </h2>
          <p>
            Our site may use cookies or similar technologies for basic
            functionality, performance measurement, and marketing attribution.
            You can control cookies through your browser settings. Disabling
            cookies may affect some site features.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            HOW LONG WE KEEP DATA
          </h2>
          <p>
            We retain quote and job records for as long as needed to provide
            service, maintain business records, resolve disputes, and meet legal
            or accounting requirements. Photos submitted for quoting may be kept
            with the related lead or job file and deleted or anonymized when no
            longer needed for those purposes.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            YOUR CHOICES
          </h2>
          <p>
            You may request access to or correction of personal information we
            hold about you, or ask us to delete information where applicable law
            allows, by emailing {BRAND.email}. We may need to verify your
            identity before fulfilling a request. Some records must be retained
            for legitimate business or legal reasons.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            CHILDREN
          </h2>
          <p>
            Our services are directed to adults arranging junk removal. We do
            not knowingly collect personal information from children under 13.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            SECURITY
          </h2>
          <p>
            We use reasonable administrative, technical, and organizational
            measures to protect personal information. No method of transmission
            or storage is completely secure; please use care when sending photos
            or personal details electronically.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            CHANGES TO THIS POLICY
          </h2>
          <p>
            We may update this Privacy Policy from time to time. The &quot;Last
            updated&quot; date at the top will change when we do. Continued use
            of our site or services after an update means you acknowledge the
            revised policy.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            CONTACT
          </h2>
          <p>
            Questions about privacy? Email{" "}
            <a href={BRAND.emailHref} className="text-bright hover:text-white">
              {BRAND.email}
            </a>{" "}
            or call{" "}
            <a href={BRAND.phoneHref} className="text-bright hover:text-white">
              {BRAND.phone}
            </a>
            .
          </p>
        </section>
      </article>
    </SiteShell>
  );
}
