import type { Metadata } from "next";
import { buildPageMetadata } from "@/lib/seo";
import { getBreadcrumbSchema } from "@/lib/schema";
import { JsonLd } from "@/components/seo/JsonLd";
import { SiteShell } from "@/components/layout/SiteShell";
import { Breadcrumbs } from "@/components/shared/Breadcrumbs";
import { BRAND, SITE_URL } from "@/lib/constants";

export const metadata: Metadata = buildPageMetadata({
  title: "Privacy Policy | Junk Command",
  description:
    "Privacy policy for Junk Command junk removal — how we handle quote forms, photos, phone/SMS, and GoHighLevel CRM data for Port Huron customers.",
  path: "/privacy",
});

const UPDATED = "August 26, 2026";
const SUPPORT_EMAIL = "dan@getjunkcommand.com";
const MAILING_ADDRESS = "4576 11th St, Smiths Creek, MI 48074";
const SMS_NON_SHARING =
  "No mobile information will be shared with third parties/affiliates for marketing/promotional purposes. Information sharing to subcontractors in support services, such as customer service, is permitted. All other use case categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.";

export default function PrivacyPage() {
  const crumbs = [
    { name: "Home", href: "/" },
    { name: "Privacy Policy", href: "/privacy" },
  ];

  return (
    <SiteShell>
      <JsonLd data={getBreadcrumbSchema(crumbs)} />
      <section className="border-b border-[rgba(0,135,255,0.2)]">
        <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8">
          <Breadcrumbs items={crumbs} />
          <h1 className="mt-2 font-display text-4xl tracking-[0.06em] text-white sm:text-5xl">
            PRIVACY POLICY
          </h1>
          <p className="mt-4 text-sm text-muted">Last updated: {UPDATED}</p>
        </div>
      </section>

      <article className="mx-auto max-w-3xl space-y-10 px-4 py-12 text-muted sm:px-6 lg:px-8">
        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            WHO WE ARE
          </h2>
          <p>
            Junk Command of Michigan DBA Junk Command (&quot;Junk Command,&quot;
            &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) provides junk
            removal and related services in Port Huron, St. Clair County, and
            surrounding Michigan communities. This Privacy Policy explains how
            we collect, use, and share information when you visit {SITE_URL},
            request a quote, call or text us, or otherwise interact with our
            business.
          </p>
          <p>
            Contact:{" "}
            <a href={BRAND.emailHref} className="text-bright hover:text-white">
              {BRAND.email}
            </a>{" "}
            ·{" "}
            <a href={BRAND.phoneHref} className="text-bright hover:text-white">
              {BRAND.phone}
            </a>
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            INFORMATION WE COLLECT
          </h2>
          <p>We collect information you provide and information generated by your use of our site and communications channels:</p>
          <ul className="list-disc space-y-2 pl-5">
            <li>
              <span className="text-white">Contact details</span> — name, phone
              number, email address, service address, and city.
            </li>
            <li>
              <span className="text-white">Job details</span> — descriptions of
              junk to remove, preferred timing, access notes, and messages you
              send through forms, SMS, or email.
            </li>
            <li>
              <span className="text-white">Photos and media</span> — images or
              videos you upload or text us to help estimate volume and quote
              accurately. Do not upload images of unrelated third parties without
              permission or sensitive documents you do not intend to share.
            </li>
            <li>
              <span className="text-white">Technical data</span> — IP address,
              browser type, device information, referring pages, and general
              usage analytics cookies or similar technologies if enabled on our
              site.
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            HOW WE USE YOUR INFORMATION
          </h2>
          <ul className="list-disc space-y-2 pl-5">
            <li>Respond to quote requests and schedule junk removal jobs</li>
            <li>Estimate pricing from photos and job descriptions</li>
            <li>Communicate by phone, SMS, or email about your request</li>
            <li>Provide customer service and follow up after completed work</li>
            <li>Improve our website, routing, and service quality</li>
            <li>Comply with legal obligations and protect against fraud or abuse</li>
            <li>
              Send service-related messages; marketing texts only where permitted
              and with consent where required
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            CRM AND SERVICE PROVIDERS (INCLUDING GOHIGHLEVEL)
          </h2>
          <p>
            We use business tools to manage leads and customer communications,
            which may include GoHighLevel (GHL) or similar customer relationship
            management (CRM), form, and messaging platforms. Information you
            submit through quote forms, photo uploads, or conversations may be
            stored in those systems so our team can respond, schedule, and keep
            records of your job.
          </p>
          <p>
            Service providers process data on our behalf under contractual
            obligations to protect it and use it only for providing their
            services to us (hosting, CRM, SMS/email delivery, and analytics). We
            do not sell your personal information. Mobile information and SMS
            opt-in data are not shared with third parties or affiliates for
            marketing or promotional purposes; see SMS / Text Messaging below.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            PHONE, SMS, AND CALL RECORDING
          </h2>
          <p>
            When you call or text {BRAND.phone}, we use your number and message
            content to provide quotes and service. Message and data rates may
            apply. SMS program terms, including how to opt out by replying STOP,
            are described in the SMS / Text Messaging section below.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            SMS / Text Messaging
          </h2>
          <p>
            Junk Command of Michigan DBA Junk Command operates an SMS / text
            messaging program for junk removal quote follow-ups,
            appointment/scheduling confirmations, crew arrival updates, and
            post-job follow-up. We collect this information to deliver consented
            SMS messages and to keep a record of your consent.
          </p>
          <p>{SMS_NON_SHARING}</p>
          <h3 className="font-display text-xl tracking-[0.06em] text-white">
            Information We Collect
          </h3>
          <p>
            When you submit our Free Estimate form or otherwise opt in to SMS,
            we collect your phone number, name, email, job and address details,
            and photos you submit. We use this information to send the consented
            SMS messages described above and to maintain a consent record.
          </p>
          <h3 className="font-display text-xl tracking-[0.06em] text-white">
            Data Security
          </h3>
          <p>
            We protect SMS-related information in transit with TLS/HTTPS and
            limit access through access controls. GoHighLevel is our processor
            for CRM, forms, and messaging.
          </p>
          <h3 className="font-display text-xl tracking-[0.06em] text-white">
            Opt-Out
          </h3>
          <p>
            You may opt out of SMS at any time by replying STOP to{" "}
            {BRAND.phone}. After you send STOP, we will send one confirmation
            message and you will receive no further SMS from us. You may also
            contact us at{" "}
            <a
              href={`mailto:${SUPPORT_EMAIL}`}
              className="text-bright hover:text-white"
            >
              {SUPPORT_EMAIL}
            </a>{" "}
            or{" "}
            <a href={BRAND.phoneHref} className="text-bright hover:text-white">
              {BRAND.phone}
            </a>
            .
          </p>
          <h3 className="font-display text-xl tracking-[0.06em] text-white">
            Contact
          </h3>
          <p>
            Privacy questions about SMS or this policy can be sent to{" "}
            <a
              href={`mailto:${SUPPORT_EMAIL}`}
              className="text-bright hover:text-white"
            >
              {SUPPORT_EMAIL}
            </a>{" "}
            or{" "}
            <a href={BRAND.phoneHref} className="text-bright hover:text-white">
              {BRAND.phone}
            </a>
            . You may also write to us at {MAILING_ADDRESS}. General inquiries
            may still be sent to{" "}
            <a href={BRAND.emailHref} className="text-bright hover:text-white">
              {BRAND.email}
            </a>
            .
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            COOKIES AND ANALYTICS
          </h2>
          <p>
            Our site may use cookies or similar technologies for basic
            functionality, performance measurement, and marketing attribution.
            You can control cookies through your browser settings. Disabling
            cookies may affect some site features.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            HOW LONG WE KEEP DATA
          </h2>
          <p>
            We retain quote and job records for as long as needed to provide
            service, maintain business records, resolve disputes, and meet legal
            or accounting requirements. Photos submitted for quoting may be kept
            with the related lead or job file and deleted or anonymized when no
            longer needed for those purposes.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            YOUR CHOICES
          </h2>
          <p>
            You may request access to or correction of personal information we
            hold about you, or ask us to delete information where applicable law
            allows, by emailing {BRAND.email}. We may need to verify your
            identity before fulfilling a request. Some records must be retained
            for legitimate business or legal reasons.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            CHILDREN
          </h2>
          <p>
            Our services are directed to adults arranging junk removal. We do
            not knowingly collect personal information from children under 13.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            SECURITY
          </h2>
          <p>
            We use reasonable administrative, technical, and organizational
            measures to protect personal information. No method of transmission
            or storage is completely secure; please use care when sending photos
            or personal details electronically.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            CHANGES TO THIS POLICY
          </h2>
          <p>
            We may update this Privacy Policy from time to time. The &quot;Last
            updated&quot; date at the top will change when we do. Continued use
            of our site or services after an update means you acknowledge the
            revised policy.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-display text-2xl tracking-[0.06em] text-white">
            CONTACT
          </h2>
          <p>
            Questions about privacy? Email{" "}
            <a
              href={`mailto:${SUPPORT_EMAIL}`}
              className="text-bright hover:text-white"
            >
              {SUPPORT_EMAIL}
            </a>{" "}
            or{" "}
            <a href={BRAND.emailHref} className="text-bright hover:text-white">
              {BRAND.email}
            </a>
            , call{" "}
            <a href={BRAND.phoneHref} className="text-bright hover:text-white">
              {BRAND.phone}
            </a>
            , or write to {MAILING_ADDRESS}.
          </p>
        </section>
      </article>
    </SiteShell>
  );
}
